//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
// Created via this command line: "C:\Users\Zigo\AppData\Roaming\MscrmTools\XrmToolBox\Plugins\DLaB.EarlyBoundGenerator\crmsvcutil.exe" /url:"https://education.crm2016.uds.systems/education" /namespace:"CrmEarlyBound" /out:"C:\Users\Zigo\AppData\Roaming\MscrmTools\XrmToolBox\Settings\EBG\CrmServiceContext.cs" /servicecontextname:"CrmServiceContext" /codecustomization:"DLaB.CrmSvcUtilExtensions.Entity.CustomizeCodeDomService,DLaB.CrmSvcUtilExtensions" /codegenerationservice:"DLaB.CrmSvcUtilExtensions.Entity.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.Entity.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /namingservice:"DLaB.CrmSvcUtilExtensions.NamingService,DLaB.CrmSvcUtilExtensions" /metadataproviderservice:"DLaB.CrmSvcUtilExtensions.Entity.MetadataProviderService,DLaB.CrmSvcUtilExtensions" 
//------------------------------------------------------------------------------

[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]

namespace PinkEducationPlagin.Tasks.Task_5.CrmContext
{
	
	/// <summary>
	/// Represents a source of entities bound to a CRM service. It tracks and manages changes made to the retrieved entities.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9479")]
	public partial class CrmServiceContext : Microsoft.Xrm.Sdk.Client.OrganizationServiceContext
	{
		
		/// <summary>
		/// Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public CrmServiceContext(Microsoft.Xrm.Sdk.IOrganizationService service) : 
				base(service)
		{
		}

        /// <summary>
        /// Gets a binding to the set of all <see cref="PinkEducationPlagin.Tasks.Task_5.CrmContext.new_new_pinktest_new_pinktest2"/> entities.
        /// </summary>
        public System.Linq.IQueryable<PinkEducationPlagin.Tasks.Task_5.CrmContext.new_new_pinktest_new_pinktest2> new_new_pinktest_new_pinktest2Set
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<PinkEducationPlagin.Tasks.Task_5.CrmContext.new_new_pinktest_new_pinktest2>();
			}
		}

        /// <summary>
        /// Gets a binding to the set of all <see cref="PinkEducationPlagin.Tasks.Task_5.CrmContext.new_PinkTest"/> entities.
        /// </summary>
        public System.Linq.IQueryable<PinkEducationPlagin.Tasks.Task_5.CrmContext.new_PinkTest> new_PinkTestSet
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<PinkEducationPlagin.Tasks.Task_5.CrmContext.new_PinkTest>();
			}
		}

        /// <summary>
        /// Gets a binding to the set of all <see cref="PinkEducationPlagin.Tasks.Task_5.CrmContext.new_pinktest2"/> entities.
        /// </summary>
        public System.Linq.IQueryable<PinkEducationPlagin.Tasks.Task_5.CrmContext.new_pinktest2> new_pinktest2Set
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.CreateQuery<PinkEducationPlagin.Tasks.Task_5.CrmContext.new_pinktest2>();
			}
		}
	}
}